rules:
  - name: Private Key
    regex: "-----BEGIN PRIVATE KEY-----"

  - name: Password
    regex: "(?i)password\\s*=\\s*['\\\"]?.+['\\\"]?"

  - name: API Key
    regex: "(?i)api[_-]?key\\s*=\\s*['\\\"]?.+['\\\"]?"

exclude:
  files:
    - ".git/*"
    - "devsecops-resources-basic/*"

allowlist:
  regexes:
    - "sonar.projectKey"
